//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Interface_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizedHide {
            get {
                return ((bool)(this["MinimizedHide"]));
            }
            set {
                this["MinimizedHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoHide {
            get {
                return ((bool)(this["AutoHide"]));
            }
            set {
                this["AutoHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSFS_PMDG_B737_Captain_CDU_SN {
            get {
                return ((string)(this["MSFS_PMDG_B737_Captain_CDU_SN"]));
            }
            set {
                this["MSFS_PMDG_B737_Captain_CDU_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSFS_PMDG_B737_Firstofficer_CDU_SN {
            get {
                return ((string)(this["MSFS_PMDG_B737_Firstofficer_CDU_SN"]));
            }
            set {
                this["MSFS_PMDG_B737_Firstofficer_CDU_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSFS_PMDG_B737_MCP_SN {
            get {
                return ((string)(this["MSFS_PMDG_B737_MCP_SN"]));
            }
            set {
                this["MSFS_PMDG_B737_MCP_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSFS_FBW_A32NX_Captain_MCDU_SN {
            get {
                return ((string)(this["MSFS_FBW_A32NX_Captain_MCDU_SN"]));
            }
            set {
                this["MSFS_FBW_A32NX_Captain_MCDU_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MSFS_FBW_A32NX_MCDU_SelectedDisplay {
            get {
                return ((int)(this["MSFS_FBW_A32NX_MCDU_SelectedDisplay"]));
            }
            set {
                this["MSFS_FBW_A32NX_MCDU_SelectedDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSFS_FBW_A32NX_Firstofficer_MCDU_SN {
            get {
                return ((string)(this["MSFS_FBW_A32NX_Firstofficer_MCDU_SN"]));
            }
            set {
                this["MSFS_FBW_A32NX_Firstofficer_MCDU_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MSFS_FENIX_A320_Captain_MCDU_SN {
            get {
                return ((string)(this["MSFS_FENIX_A320_Captain_MCDU_SN"]));
            }
            set {
                this["MSFS_FENIX_A320_Captain_MCDU_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0Top {
            get {
                return ((double)(this["PMDG737CDU0Top"]));
            }
            set {
                this["PMDG737CDU0Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0Left {
            get {
                return ((double)(this["PMDG737CDU0Left"]));
            }
            set {
                this["PMDG737CDU0Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("770")]
        public double PMDG737CDU0Height {
            get {
                return ((double)(this["PMDG737CDU0Height"]));
            }
            set {
                this["PMDG737CDU0Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830")]
        public double PMDG737CDU0Width {
            get {
                return ((double)(this["PMDG737CDU0Width"]));
            }
            set {
                this["PMDG737CDU0Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindowMaximized {
            get {
                return ((bool)(this["MainWindowMaximized"]));
            }
            set {
                this["MainWindowMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1Top {
            get {
                return ((double)(this["PMDG737CDU1Top"]));
            }
            set {
                this["PMDG737CDU1Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1Left {
            get {
                return ((double)(this["PMDG737CDU1Left"]));
            }
            set {
                this["PMDG737CDU1Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("770")]
        public double PMDG737CDU1Height {
            get {
                return ((double)(this["PMDG737CDU1Height"]));
            }
            set {
                this["PMDG737CDU1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("830")]
        public double PMDG737CDU1Width {
            get {
                return ((double)(this["PMDG737CDU1Width"]));
            }
            set {
                this["PMDG737CDU1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double PMDG737CDU0FontSize {
            get {
                return ((double)(this["PMDG737CDU0FontSize"]));
            }
            set {
                this["PMDG737CDU0FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0MarginTop {
            get {
                return ((double)(this["PMDG737CDU0MarginTop"]));
            }
            set {
                this["PMDG737CDU0MarginTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0MarginBottom {
            get {
                return ((double)(this["PMDG737CDU0MarginBottom"]));
            }
            set {
                this["PMDG737CDU0MarginBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0MarginLeft {
            get {
                return ((double)(this["PMDG737CDU0MarginLeft"]));
            }
            set {
                this["PMDG737CDU0MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0MarginRight {
            get {
                return ((double)(this["PMDG737CDU0MarginRight"]));
            }
            set {
                this["PMDG737CDU0MarginRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0GridWidth {
            get {
                return ((double)(this["PMDG737CDU0GridWidth"]));
            }
            set {
                this["PMDG737CDU0GridWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU0GridHeight {
            get {
                return ((double)(this["PMDG737CDU0GridHeight"]));
            }
            set {
                this["PMDG737CDU0GridHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double PMDG737CDU1FontSize {
            get {
                return ((double)(this["PMDG737CDU1FontSize"]));
            }
            set {
                this["PMDG737CDU1FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1MarginTop {
            get {
                return ((double)(this["PMDG737CDU1MarginTop"]));
            }
            set {
                this["PMDG737CDU1MarginTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1MarginBottom {
            get {
                return ((double)(this["PMDG737CDU1MarginBottom"]));
            }
            set {
                this["PMDG737CDU1MarginBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1MarginLeft {
            get {
                return ((double)(this["PMDG737CDU1MarginLeft"]));
            }
            set {
                this["PMDG737CDU1MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1MarginRight {
            get {
                return ((double)(this["PMDG737CDU1MarginRight"]));
            }
            set {
                this["PMDG737CDU1MarginRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1GridWidth {
            get {
                return ((double)(this["PMDG737CDU1GridWidth"]));
            }
            set {
                this["PMDG737CDU1GridWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PMDG737CDU1GridHeight {
            get {
                return ((double)(this["PMDG737CDU1GridHeight"]));
            }
            set {
                this["PMDG737CDU1GridHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENET {
            get {
                return ((bool)(this["ENET"]));
            }
            set {
                this["ENET"] = value;
            }
        }
    }
}
